apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQmtqbVlKZEtrTWN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1UVXhOREkwTUROYUZ3MHpOVEF6TVRNeE5ESTVNRE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMwdkZvRCtKMmhNRUJMVTBHS2VxLzk2cGl3MEJBelB1QVBIZWxyU205d2poZGExOTMweGJwNmtZOHUKbDZMYllqY1VUZnkrVlpNMTYzWXBHTUVmUnc1TDZxalBhUkNmTlArRG9Yb2ZYaHZ2M0Ftclp1S2E2aDl2Wjd3dgppQStOdTQ0UDRiUVNWZjZQZEFpTko0RDRlZzN0UUlPR1d4TVlBMXl5SWlBMmZ2VmdocWliK3c5OGJ0d21qa1hMCkN6RjdtQjN4d0tYak92MXZQYnVDV2kva1JMR0NYUnlSbklUd1FmcldjNHlOSnpYK0hHUnZaYVNyVW5hc2FidzUKOXFJVDhOd0dpU2R3K1NnRW80c2lKeDBmdDd6eVk4NGM3T2NqRk5kWkxFcHBIR3FlRUFBRm5sOFlWdlZqVHpXZwpWQVo0c3JvY0pqc3czMVVQdnAwYmc3Nms4amJKQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUcEpaNEpjNjZlbnBBKzFDMGlLUjRlRmJUYW9UQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTd4QzlQQ1JpMgo2TFNaa0E4UWttaE51NVNPVklLT2I1NERkNzQ3Wkw1RXdzTlN1bjY0d1FwS0VxUWRkaWF3Ym9Fb2RxL1hyZkV6Ck1Lc2RxbHMwMmpyaXdmeG5ML083aW82N2VhVzRVeEJ6cXE4N1BDWWJCdEFaUlNRU2pxN2NiV1prbFJCSGZKZ0MKcDdBcjRkbTJEWUNMZ2JySnJFcDZjdUp4eWNxdVQ3a0hSQ0VkMXJ2cGE3MkxTNW5iQllPSCsxRUJ0QkVJRkloSQpPR0Jqa3VjdVQ2NkVtNkNSc1NCTkF4SXBzRUpPU0xWaVl4K1JLMkExblkxZ0QzNEJrZ3hKbWVpdUxTSFpsWVBGCk9rK1RsQXEvZnZrTy9aZXpnQ04yTmNsRzRDVGpuTGR1b09JR0lhLzFqbG53Rks5MjZrdGlITFZlREFHZmVlMUIKbEo3clFWRGs1ckVRCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://E62743C2D9022D847851D434C93B52B1.gr7.us-east-1.eks.amazonaws.com
  name: dev-cluster.us-east-1.eksctl.io
contexts:
- context:
    cluster: dev-cluster.us-east-1.eksctl.io
    user: i-0cea0ab0176215c0f@dev-cluster.us-east-1.eksctl.io
  name: i-0cea0ab0176215c0f@dev-cluster.us-east-1.eksctl.io
current-context: i-0cea0ab0176215c0f@dev-cluster.us-east-1.eksctl.io
kind: Config
preferences: {}
users:
- name: i-0cea0ab0176215c0f@dev-cluster.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - dev-cluster
      - --region
      - us-east-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
